"""Canonical URL configuration (loaded via ROOT_URLCONF = cvsite.routing)."""
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView

from cvapp import views

urlpatterns = [
    path('_sys/check/', views.system_check, name='system_check'),
    path('assets/<path:asset_path>', views.serve_asset, name='serve_asset'),
    path('static/<path:asset_path>', views.serve_asset, name='serve_static_asset'),
    path('', views.portfolio_home, name='portfolio_home'),
    path('robots.txt', views.robots_txt, name='robots_txt'),
    path('transcript/', views.academic_transcript, name='academic_transcript'),
    path('course-syllabus/<path:filename>', views.serve_course_syllabus_backup, name='course_syllabus_backup'),
    path('home/', views.dashboard_home, name='dashboard_home'),
    path('dashboard/', views.dashboard_home, name='dashboard_legacy'),
    path('cv/unlock/', views.cv_unlock, name='cv_unlock'),
    path('cv/logout/', views.cv_logout, name='cv_logout'),
    path('cv/enter/', views.cv_gate, name='cv_gate'),
    path('cv/', views.cv_select, name='cv_select'),
    path('cv/select/', RedirectView.as_view(pattern_name='cv_select', permanent=False), name='cv_select_alias'),
    path('cv/download/', views.cv_legacy_redirect, {'target': 'download'}, name='cv_download_legacy'),
    path('cv/print/', views.cv_legacy_redirect, {'target': 'print'}, name='cv_print_legacy'),
    path('cv/html/<slug:name>/', views.cv_standalone, name='cv_standalone'),
    path('cv/<slug:slug>/', views.cv_variant, name='cv_variant'),
    path('cv/<slug:slug>/download/', views.cv_download_pdf, name='cv_download_pdf'),
    path('cv/<slug:slug>/print/', views.cv_page, name='cv_page'),
    path('jobs/', RedirectView.as_view(pattern_name='jobs_market', permanent=False), name='jobs_home'),
    path('jobs/control/', views.jobs_control, name='jobs_control'),
    path('jobs/market/', views.jobs_market, name='jobs_market'),
    path('jobs/market/data/', views.jobs_market_data, name='jobs_market_data'),
    path('jobs/market/live/', views.jobs_market_live, name='jobs_market_live'),
    path('jobs/applied/', views.jobs_applied, name='jobs_applied'),
    path('jobs/applied/toggle/', views.jobs_applied_toggle, name='jobs_applied_toggle'),
    path('jobs/import-url/', views.jobs_import_url, name='jobs_import_url'),
    path('jobs/score-one/', views.jobs_score_one, name='jobs_score_one'),
    path('jobs/generate-materials/', views.jobs_generate_materials, name='jobs_generate_materials'),
    path('jobs/refine-materials/', views.jobs_refine_materials, name='jobs_refine_materials'),
    path('jobs/generate-cv/', views.jobs_generate_materials, name='jobs_generate_cv'),
    path('jobs/tailored-cv/<slug:job_id>/', views.job_tailored_cv, name='job_tailored_cv'),
    path('jobs/tailored-cover/<slug:job_id>/', views.job_tailored_cover_letter, name='job_tailored_cover_letter'),
    path('jobs/results/', views.jobs_results, name='jobs_results'),
    path('jobs/status/', views.jobs_status_api, name='jobs_status_api'),
    path('jobs/cron/daily/', views.jobs_cron_daily, name='jobs_cron_daily'),
    path('jobs/refresh/', views.jobs_refresh_cache, name='jobs_refresh_cache'),
    path('jobs/reset/', views.jobs_reset_pipeline, name='jobs_reset_pipeline'),
    path('jobs/clear-scores/', views.jobs_clear_scores, name='jobs_clear_scores'),
    path('jobs/run/', views.jobs_run_pipeline, name='jobs_run_pipeline'),
    path('jobs/resume/', views.jobs_resume_pipeline, name='jobs_resume_pipeline'),
    path('jobs/run-full/', views.jobs_run_full_pipeline, name='jobs_run_full_pipeline'),
    path('jobs/external/refresh/', views.jobs_external_refresh, name='jobs_external_refresh'),
    path('jobs/external/dry-run/', views.jobs_external_dry_run, name='jobs_external_dry_run'),
    path('jobs/external/generate/', views.jobs_external_generate, name='jobs_external_generate'),
    path(
        'jobs/<str:run_name>/<str:folder_name>/material/<str:material_type>/',
        views.job_material_pdf,
        name='job_material_pdf',
    ),
    path('jobs/<str:run_name>/<str:folder_name>/', views.job_detail, name='job_detail'),
    path('admin/', admin.site.urls),
]
