"""
Django settings for cvsite project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from decouple import config


def _config_bool(name: str, *, default: bool = False) -> bool:
    """Parse env booleans; tolerate common typos like 'fals' on Render."""
    raw = os.getenv(name, '').strip().lower()
    if not raw:
        return default
    if raw in ('1', 'true', 'yes', 'on', 't'):
        return True
    if raw in ('0', 'false', 'no', 'off', 'f', 'fals', 'flase'):
        return False
    try:
        return config(name, default=default, cast=bool)
    except ValueError:
        return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Allow importing the integrated local jobsearch package.
JOB_SEARCH_ROOT = BASE_DIR / 'jobsearch'
if JOB_SEARCH_ROOT.exists():
    sys.path.insert(0, str(JOB_SEARCH_ROOT))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-egkiou&a-4ph&o&6ubodk!*$-hxg2n9k_sbne+1t7+%hli^cmg')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _config_bool('DEBUG', default=True)

_allowed = [h.strip() for h in config('ALLOWED_HOSTS', default='127.0.0.1,localhost').split(',') if h.strip()]
_render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if _render_host and _render_host not in _allowed:
    _allowed.append(_render_host)
ALLOWED_HOSTS = _allowed


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cvapp.apps.CvappConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'cvapp.cv_middleware.CVAccessMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cvsite.routing'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'cvapp' / 'templates',
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cvapp.context_processors.candidate_context',
                'cvapp.context_processors.profile_context',
                'cvapp.context_processors.pipeline_status_context',
                'cvapp.context_processors.dashboard_styles',
                'cvapp.context_processors.topbar_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'cvsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'cvapp' / 'static']

# Manifest storage breaks {% static %} in dev without collectstatic — use plain storage locally.
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    # Manifest storage 500s when any asset is missing from staticfiles.json on deploy.
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JOB_DEFAULT_MIN_SCORE = config('JOB_DEFAULT_MIN_SCORE', default=50, cast=int)
JOB_DEFAULT_MAX_JOBS = config('JOB_DEFAULT_MAX_JOBS', default=150, cast=int)

# Site password — ON when ENABLE_CV_PASSWORD=true and CV_ACCESS_PASSWORD is set.
# Accept common Render typo ENABLE_CV_PASSORD (missing W).
if not os.getenv('ENABLE_CV_PASSWORD', '').strip() and os.getenv('ENABLE_CV_PASSORD', '').strip():
    os.environ['ENABLE_CV_PASSWORD'] = os.environ['ENABLE_CV_PASSORD']
ENABLE_CV_PASSWORD = _config_bool('ENABLE_CV_PASSWORD', default=True)
CV_ACCESS_PUBLIC = not ENABLE_CV_PASSWORD
CV_ACCESS_REQUIRED = ENABLE_CV_PASSWORD
CV_ACCESS_PASSWORD = (
    config('CV_ACCESS_PASSWORD', default='').strip() if ENABLE_CV_PASSWORD else ''
)

# Stay signed in on your devices until you click Sign out (when password gate is on).
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
# Render free tier: avoid SQLite session writes (common 500 after unlock POST).
if not DEBUG:
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# HTTPS hardening on Render (production only).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Public URL for QR codes and consolidated academic record links on exported CVs.
CV_PUBLIC_BASE_URL = config('CV_PUBLIC_BASE_URL', default='').strip()
